### ISSUE TITLE
How to add tags to a post?

### ISSUE THREAD

**Issue by soisme** [letrunghieu/wordpress-xmlrpc-client#14]
I tried the following they don't work.

$wpClient->newPost($title, $message, array('terms' => array('category' => array($category)), 'mt_keywords' => 'tag'));

 $wpClient->newPost($title, $message, array('terms' => array('category' => array($category)), 'mt_keywords' => array('tag')));

**Comment by katona44** [comment]
Could you give an example how it works in the new version? Been trying to figure it out for hours.
