### ISSUE TITLE
Getting 'XML-RPC server accepts POST requests only'

### ISSUE THREAD

**Issue by starthereau** [letrunghieu/wordpress-xmlrpc-client#15]
Hi again,

Again been using the client successfully for months, now in the last few days I am getting this error in the _sendRequest() function:

XML-RPC server accepts POST requests only

This is the function, quite clearly using the POST method?

![2015-01-16_08h59_27](https://cloud.githubusercontent.com/assets/2666593/5768610/073fb9aa-9d5e-11e4-9e7e-eba96ce5d100.png)

The var_dump shows the below on execution:

![image](https://cloud.githubusercontent.com/assets/2666593/5768625/2c091286-9d5e-11e4-9906-e654fe338e93.png)

Any idea guys?

Cheers,
Steve.

**Comment by starthereau** [comment]
I updated to the latest version, but still get the same response in the var_dump:

![2015-01-16_09h22_49](https://cloud.githubusercontent.com/assets/2666593/5768956/6655fde8-9d61-11e4-8912-dd21cd512960.png)

**Comment by WarrenMoore** [comment]
A stab in the dark but are you attempting to connect to a WordPress.com blog, or self-hosted?

A recent change occurred whereby WordPress now forces you to connect over HTTPS when making XML-RPC calls to WordPress.com blogs,

**Comment by starthereau** [comment]
Thanks Warren, that must have been it, we're now self-hosting so no longer an issue.

Steve.
