### ISSUE TITLE
The requested PHP extension xmlrpc is missing from your system.

### ISSUE THREAD

**Issue by phuclh** [letrunghieu/wordpress-xmlrpc-client#16]
I can not install your package. I got a message:
`The requested PHP extension xmlrpc is missing from your system.`

Please help me!! Thank you very much.

**Comment by letrunghieu** [comment]
You need enable PHP xmlrpc extension to use this library.

For example, in Ubuntu, run these command to enable the extension.: `sudo apt-get install php5-xmlrpc` and `sudo php5enmod xmlrpc`

**Comment by phuclh** [comment]
Thank you very much :D. But how can I upload a featured image?

**Comment by letrunghieu** [comment]
* First, use [`uploadFile`](http://letrunghieu.github.io/wordpress-xmlrpc-client/api/class-HieuLe.WordpressXmlrpcClient.WordpressClient.html#_uploadFile) method to upload your image to Wordpress. Get its ID from the returning array.
* Next, set the `$content['post_thumbnail']` to that ID and using [`newPost`](http://letrunghieu.github.io/wordpress-xmlrpc-client/api/class-HieuLe.WordpressXmlrpcClient.WordpressClient.html#_newPost) or [`editPost`](http://letrunghieu.github.io/wordpress-xmlrpc-client/api/class-HieuLe.WordpressXmlrpcClient.WordpressClient.html#_editPost) to attach the uploaded image as the post feature image.
