### ISSUE TITLE
Encoding problems / wrong encoding

### ISSUE THREAD

**Issue by OskHa** [letrunghieu/wordpress-xmlrpc-client#17]
Please set in **_sendRequest()** 

Change from:
`` $response = xmlrpc_decode($body); ``

To:
``$response = xmlrpc_decode($body,"UTF-8");``

Or best define the encoding.

**Comment by letrunghieu** [comment]
This is already implemented in [v2.4.1](https://github.com/letrunghieu/wordpress-xmlrpc-client/blob/2.4.1/src/WordpressClient.php#L847). You can run `composer update`.
