### ISSUE TITLE
All methods return null

### ISSUE THREAD

**Issue by ryanschott** [letrunghieu/wordpress-xmlrpc-client#19]
I'm noticing that all methods return null regardless of what the documentation says the return type should be. I am also noticing that file uploads are not working properly. What is going on?

**Comment by ryanschott** [comment]
I was able to get the regular post to work, but it doesn't return an ID. The file upload doesn't work at all. No errors are being returned.

**Comment by ryanschott** [comment]
the xmlrpc_decode($body, 'UTF-8') function should be xmlrpc_decode(trim($body), 'UTF-8') because of a  bug in xmlrpc_decode. See comments in http://php.net/manual/en/function.xmlrpc-decode.php

**Comment by ryanschott** [comment]
I figured out that the name that is given to the file must have the same extension as what is being uploaded. IE: It's a file name not the name of the object in wordpress. Interesting.

**Comment by letrunghieu** [comment]
Thank you @ryanschott, I'll check with my new Wordpress installation and update the status for this package this week.

**Comment by ErvinLlojku** [comment]
Hello,
the tests were not passing due to mime_content_type being deprecated (WordpressClientTest.php : 992 ) . Refer to this question in stack 
http://stackoverflow.com/questions/14809054/mime-content-type-function-not-working
Please consider updating this part aswell.

**Comment by letrunghieu** [comment]
Can you tell me which PHP version did you use and the result of the PHPUnit test?

**Comment by ErvinLlojku** [comment]
![mime_1](https://cloud.githubusercontent.com/assets/11721817/13629136/62811422-e5d7-11e5-9cca-9f625be7eb9c.png)

Please check the screenshot.

P.s: Thank you for the awesome work and sharing knowledge with other devs. Have a nice and productive day.

**Comment by ErvinLlojku** [comment]
@letrunghieu I confirm that my tests are passing now. It may have been something with my php or smth. Thnx for the help
