### ISSUE TITLE
using your 2.0 api, worpress are blaclisting me

### ISSUE THREAD

**Issue by etouraille** [letrunghieu/wordpress-xmlrpc-client#27]
Hello, when I use your 2.0 version of your client, my wordpress blog are banning me, with this message : 

```
<h2>You don't have permission to access this server.</h2>
        <p>Your IP address <code>{myIP}</code> has been blacklisted due to suspicious behaviour.</p>
```

**Comment by letrunghieu** [comment]
This is not the problem of the library but the Wordpress server. It may be set to block requests from non-human agents.
