### ISSUE TITLE
 $wpClient->newTerm(); add new term in taxonomy use  file WordpressClient.php show error

### ISSUE THREAD

**Issue by thanhlvkc** [letrunghieu/wordpress-xmlrpc-client#30]
Fatal error: Call to undefined function HieuLe\WordpressXmlrpcClient\xmlrpc_encode_request() in E:\VERTRIGO_SERVER\www\convert_rpc\WordpressClient.php on line 901

**Comment by letrunghieu** [comment]
Hi,

Thanks for using this package. You have to enable xmlrpc extension in your `php.ini` file first.

**Comment by thanhlvkc** [comment]
thank you !
