### ISSUE TITLE
what to do when I dont want to use composer 

### ISSUE THREAD

**Issue by kareemzok** [letrunghieu/wordpress-xmlrpc-client#32]
How to update the code when  we dont use the composer  ??

**Comment by kareemzok** [comment]
@

**Comment by letrunghieu** [comment]
Hi @kareemzok 

If you don't use Composer, you can download the latest release at https://github.com/letrunghieu/wordpress-xmlrpc-client/releases/tag/2.5.0 then include all files inside the `src` sub directory into your project. You can see [this section](https://github.com/letrunghieu/wordpress-xmlrpc-client#your-project-has-used-composer) of the README file more details.

**Comment by kareemzok** [comment]
Yes i did exactly same , it worked on my local but when i uploaded the file on my hosting i got "HTTP ERROR 500" .  Any idea ? plz

**Comment by kareemzok** [comment]
the error is : "PHP Parse error:  syntax error, unexpected T_STRING "  when i use  use HieuLe\WordpressXmlrpcClient;
`$wpClient = new \HieuLe\WordpressXmlrpcClient\WordpressClient();`

**Comment by letrunghieu** [comment]
Could you please tell me the version of PHP on your local machine as well as your hosting?

**Comment by kareemzok** [comment]
Php version on local : 5.6.24
Php version on my hosting : 5.2.17
I need to upgrade it ?

**Comment by letrunghieu** [comment]
Hi @kareemzok 

This package require PHP 5.3 or above 😄 You should upgrade the PHP version in your hosting.

**Comment by kareemzok** [comment]
hahaha i thought about that , well thanks for your support :)  👍  will do that and if it is worked i ll close this thread haha

**Comment by kareemzok** [comment]
Thanks it works now  but got other error but i ll  check them later
